trulelea docker huioker

diff --git a/.docker/nest/Dockerfile b/.docker/nest/Dockerfile
--- a/.docker/nest/Dockerfile
+++ b/.docker/nest/Dockerfile
@@ -1,50 +1,39 @@
 FROM node:20-alpine AS base
+
+FROM base AS builder
+ENV TURBO_TELEMETRY_DISABLED=1
 RUN apk update
 RUN apk add --no-cache libc6-compat
-RUN yarn global add turbo@2.0.9
-
-# Build stage
-FROM base AS builder
-ENV NEXT_TELEMETRY_DISABLED=1
-ENV TURBO_TELEMETRY_DISABLED=1
 WORKDIR /app
+RUN yarn global add turbo@^2
 COPY . .
-RUN turbo prune --scope=api --docker
+RUN turbo prune api --docker
 
-# Install dependencies
 FROM base AS installer
-ENV NEXT_TELEMETRY_DISABLED=1
 ENV TURBO_TELEMETRY_DISABLED=1
+RUN apk update
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
+COPY .gitignore .gitignore
 COPY --from=builder /app/out/json/ .
 COPY --from=builder /app/out/yarn.lock ./yarn.lock
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+RUN yarn upgrade
+COPY --from=builder /app/out/full/ .
+RUN yarn turbo run build --filter=api
 
-# Finalize build
-FROM base AS final
+FROM base AS runner
+ENV PORT=3000
 ENV NODE_ENV=production
-ENV NEXT_TELEMETRY_DISABLED=1
 ENV TURBO_TELEMETRY_DISABLED=1
 WORKDIR /app
-COPY --from=installer /app/ .
-COPY --from=builder /app/out/full/ .
-RUN turbo run build --filter=api
-CMD ["ls", "-la"]
-
-# Run stage
-#FROM base AS runner
-#ENV PORT=80
-#ENV NODE_ENV=production
-#ENV NEXT_TELEMETRY_DISABLED=1
-#ENV TURBO_TELEMETRY_DISABLED=1
-#WORKDIR /app
-#RUN addgroup -g 1001 -S nodejs
-#RUN adduser -S nestjs -u 1001
-#COPY --from=final --chown=nestjs:nodejs /app/applications/api/dist .
-#COPY --from=final --chown=nextjs:nodejs /app/applications/api/node_modules ./node_modules
-#USER nestjs
-#EXPOSE 80
-#CMD ["node", "main.js"]
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nest
+USER nest
+COPY --from=installer --chown=nest:nodejs /app/applications/api/build ./
+COPY --from=installer --chown=nest:nodejs /app/node_modules ./node_modules
+EXPOSE 3000
+CMD ["node", "main.js"]
diff --git a/.docker/next/Dockerfile b/.docker/next/Dockerfile
--- a/.docker/next/Dockerfile
+++ b/.docker/next/Dockerfile
@@ -1,56 +1,45 @@
 ARG NEXT_PUBLIC_DOMAIN
 
 FROM node:20-alpine AS base
+
+FROM base AS builder
+ENV NODE_ENV=production
+ENV TURBO_TELEMETRY_DISABLED=1
 RUN apk update
 RUN apk add --no-cache libc6-compat
-RUN yarn global add turbo@2.0.9
-
-# Build stage
-FROM base AS builder
-ENV NEXT_TELEMETRY_DISABLED=1
-ENV TURBO_TELEMETRY_DISABLED=1
 WORKDIR /app
+RUN yarn global add turbo@^2
 COPY . .
 RUN turbo prune web --docker
 
-# Install dependencies
 FROM base AS installer
-ENV NEXT_TELEMETRY_DISABLED=1
+ENV NODE_ENV=production
 ENV TURBO_TELEMETRY_DISABLED=1
+RUN apk update
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
+COPY .gitignore .gitignore
 COPY --from=builder /app/out/json/ .
 COPY --from=builder /app/out/yarn.lock ./yarn.lock
 RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
-
-# Finalize build
-FROM base AS final
-ENV NODE_ENV=production
-ENV NEXT_TELEMETRY_DISABLED=1
-ENV TURBO_TELEMETRY_DISABLED=1
-ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
-WORKDIR /app
-COPY --from=installer /app/ .
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 COPY --from=builder /app/out/full/ .
-RUN turbo run build --filter=web
+RUN yarn turbo run build --filter=web
 
-# Run stage
 FROM base AS runner
-ENV PORT=80
+ENV PORT=3000
 ENV NODE_ENV=production
-ENV NEXT_TELEMETRY_DISABLED=1
 ENV TURBO_TELEMETRY_DISABLED=1
-ENV NEXT_PUBLIC_DOMAIN=${NEXT_PUBLIC_DOMAIN}
 WORKDIR /app
-RUN addgroup -g 1001 -S nodejs
-RUN adduser -S nextjs -u 1001
-COPY --from=final --chown=nextjs:nodejs /app/applications/web/public ./public
-COPY --from=final --chown=nextjs:nodejs /app/applications/web/.next/standalone/node_modules ./node_modules
-COPY --from=final --chown=nextjs:nodejs /app/applications/web/.next/standalone/applications/web/.next ./.next
-COPY --from=final --chown=nextjs:nodejs /app/applications/web/.next/standalone/applications/web/server.js ./server.js
-COPY --from=final --chown=nextjs:nodejs /app/applications/web/.next/static ./.next/static
-USER nextjs
-EXPOSE 80
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 next
+USER next
+COPY --from=installer --chown=next:nodejs /app/applications/web/public ./public
+COPY --from=installer --chown=next:nodejs /app/applications/web/.next/standalone/node_modules ./node_modules
+COPY --from=installer --chown=next:nodejs /app/applications/web/.next/standalone/applications/web/.next ./.next
+COPY --from=installer --chown=next:nodejs /app/applications/web/.next/standalone/applications/web/server.js ./server.js
+COPY --from=installer --chown=next:nodejs /app/applications/web/.next/static ./.next/static
+EXPOSE 3000
 CMD ["node", "server.js"]
